name: Test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

env:
  MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
  TOKEN_SECRET: ${{secrets.TOKEN_SECRET}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Running test
        run: npm test
